### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'before' of null"

### ISSUE THREAD

**Issue by StanleeLOD** [privatenumber/vue-frag#13]
I have table with sortable columns. In Cell component I'm using v-frag.
It's working fine when items is hiding but when I change order I see error like this

**Comment by privatenumber** [comment]
Thanks for reporting @StanleeLOD 

Do you mind sharing your code in a Codepen for me to debug?

Here's a base template using Vue frag: https://codepen.io/hirokiosame/pen/PoNVZbV

**Comment by StanleeLOD** [comment]
Hi @privatenumber. Thank you for your fast response.
Actually, I can't reproduce it on Codepen and can't figure out the reason this bug is happening.

I have a table with columns that might use `v-frag`, when I change the order of columns in some cases it causes the error.
I'll try to fix my Codepen and came back with this issue when it will be reproduced
Thanks
