### ISSUE TITLE
Error in nextTick: "TypeError: Cannot read property 'after' of undefined" (when using slots with v-if)

### ISSUE THREAD

**Issue by doogi** [privatenumber/vue-frag#21]
Hi there,
today I faced an issue with `vue-frag` in my implementation. I saw you did several tests for `v-if` scenarios but might miss a case when you have a `slot` with `v-if` causing a fatal error breaking the flow. 
I managed to create some base test case for the issue but unfortunately didn't manage to fix it by myself without breaking other tests, so hopefully, you'll find it useful to prepare a proper fix :) 
```
	test('v-if slot', async () => {
		const TestComponent = {
			template: `
				<div v-frag>
					<slot />
				</div>
			`,
			directives: {
				frag,
			},
		};

		const usage = {
			template: `
				<div class="wrapper">
					<test-component><div v-if="show">A</div></test-component>
				</div>
			`,
			components: {
				TestComponent,
			},
			data() {
				return {
					show: false,
				};
			},
		};

		const empty = '<div class="wrapper">\n  <!---->\n</div>';
		const ifTrue = '<div class="wrapper">\n  <div>A</div>\n</div>';

		const wrapper = mount(usage);
		expect(wrapper.html()).toBe(empty);

		wrapper.setData({show: true});
		await wrapper.vm.$nextTick();
		expect(wrapper.html()).toBe(ifTrue);

		wrapper.setData({show: false});
		await wrapper.vm.$nextTick();
		// expect(wrapper.html()).toBe(empty);

		wrapper.setData({show: true});
		await wrapper.vm.$nextTick();
		expect(wrapper.html()).toBe(ifTrue);
	});
```
The penultimate expectation (after setting show to false) that I commented out is also failing, but I wanted to show you the failing scenario I faced which is an error on the second attempt to show slot contents.

**Comment by privatenumber** [comment]
Thanks for the bug report @doogi !

I just released a fix ^
