### ISSUE TITLE
[nuxt] Html elements order is not preserved during navigation via nuxt-link

### ISSUE THREAD

**Issue by kwolniak** [privatenumber/vue-frag#27]
You can see this problem here: https://codesandbox.io/s/dazzling-currying-gdyi0?file=/pages/index.vue

1. We have there two pages (index, about) and one layout (default).
1. Notice that `v-frag` is used only on index page. 
1. When you navigate between pages (use links in header) you can see that page content is loading below all layout elements.

Notice:
1. Section number 2) the green one, should be always in the middle.
1. It happens only when navigating via links, it looks like server side rendering works fine (go to about page and click refresh button in codesandbox internal "browser").
1. When you navigate from **about** (page without v-frag) to **index** (page with v-frag) it works fine (to see this, refresh codesandbox internal browser on about page).

**Comment by privatenumber** [comment]
Thanks for the issue with a reproduction. I hadn't tested it with routers or Nuxt so this is great.

Will try to look into it this weekend.

**Comment by privatenumber** [comment]
More minimal reproduction: https://codesandbox.io/s/summer-http-4jjyv

Also worth noting that it works fine with a plain Vue Router setup: https://jsfiddle.net/hirokiosame/1mf5ky86/

Currently looking like a Nuxt issue

**Comment by privatenumber** [comment]
Got a reproduction using `<transition>`: https://jsfiddle.net/hirokiosame/4Lyjwpcs/

Seems the issue is that `nextSibling` isn't patched. Will release fix soon.
