### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by Moghul** [privatenumber/vue-frag#28]
By default when I load a page using this directive in IE11 I get the error

`Error in directive frag inserted hook: "TypeError: Unable to get property 'apply' of undefined or null reference"`

This is pretty simple to fix by adding a polyfill for ParentElement.append and one for ChildElement.replaceWith.

The problem is that after I add the polyfill, I run into another issue altogether:

`Error in directive frag inserted hook: "Error: Out of stack space"`

It's pretty difficult to debug for me as the stack trace just looks like 
![image](https://user-images.githubusercontent.com/17046245/114702778-c8e89000-9d24-11eb-97a9-590614fc7d57.png)

Any ideas on what the issue is or what the solution is?

**Comment by privatenumber** [comment]
Sorry, I haven't had access to IE11 but I can look into testing it later.

Can you provide reproduction steps?

From your report, I don't know what code you used to produce the error or the polyfill you used.

**Comment by Moghul** [comment]
The polyfills I tried are from here https://www.npmjs.com/package/element-polyfill
And the code is fairly simple. In the template, I have a div with v-frag on it, and inside that div I have multiple elements like
![image](https://user-images.githubusercontent.com/17046245/114985638-51853e80-9e93-11eb-8e9f-e17416a62286.png)

I think it should be pretty easy to get access to IE11 if you get one of these vms
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Comment by privatenumber** [comment]
Thought about this some more, and I'm not sure if I can justify spending my time to add IE11 support. IE11 support is being deprecated everywhere.

PR welcome if you want to give it a shot.

Happy to reconsider if this package gains more popularity & adoption (GH stars/npm downloads).

**Comment by Moghul** [comment]
Damn. That's really unfortunate. Thanks for the honesty, though.
