### ISSUE TITLE
Can not work with Sortable.js

### ISSUE THREAD

**Issue by MisicDemone** [privatenumber/vue-frag#33]
Example: https://codesandbox.io/s/eloquent-shaw-f9cu9?file=/src/App.vue

**Comment by privatenumber** [comment]
Thanks for the reproduction.

Sorry, but I'm going to close this with a won't fix.

Vue-frag is only designed to work with Vue.js. The way it works is by patching DOM API nodes to trick anyone interacting with it to think that the root element is still in the DOM. As a side effect, it will trick other libraries like SortableJs that the root element is still there when it's actually not.

I'm afraid adding further support to selectively choose when to return fake data and when to return real data (if that's even possible) will bloat the library unnecessarily.
