### ISSUE TITLE
Error on Nuxt when use v-frag inside an transition component

### ISSUE THREAD

**Issue by dbarjs** [privatenumber/vue-frag#34]
Error: `TypeError: Cannot read property 'splice' of undefined`

## How to reproduce

Create a Nuxt project and add this component (just an dumb example):

Component with v-frag:
```vue
<template>
  <div v-frag>
    <button>
      <slot></slot>
    </button>
    <div>
      <p>Content</p>
    </div>
  </div>
</template>
```

Add this component in a page (like `index.vue`) using an transition:

Page :
```vue
<template>
  <transition name="fade">
    <div v-if="isVisible">
      <ComponentWithVFrag>...</ComponentWithVFrag>
    </div>
  </transition>
</template>
```

Run `yarn dev` and open the page in the browser and open the console:
![Screenshot from 2021-06-03 10-39-56](https://user-images.githubusercontent.com/5067222/120654500-23b28400-c458-11eb-98ef-43ebf0af4039.png)

The page will break and you will not be able to view the component's content.

If I remove the transition component, the page will work normally.

## Version details
nuxt@npm:2.15.6
vue-frag@npm: 1.1.5

**Comment by privatenumber** [comment]
Works fine for me: https://codesandbox.io/s/confident-butterfly-wg5tw?file=/pages/index.vue

**Comment by privatenumber** [comment]
Closing as this works fine in the Code Sandbox example.

If you can make a reproduction of the bug, please share it!
