### ISSUE TITLE
Add sourcemaps

### ISSUE THREAD

**Issue by 3nuc** [privatenumber/vue-frag#36]
Right now when you get an error related to vue-frag, the error will read like this (I use Firefox - the Chrome error message is a bit different in this case):
`can't access property Symbol(), a is null`
Notice the `a` - there's no variable named `a` in the enteriety of src/frag.js. This is because the `a` comes from the already minified file frag.esm.js
The above error happens on line 1 of frag.esm.js, but that's not very helpful because the whole file is just one line (again - minification)
![image](https://user-images.githubusercontent.com/5359825/130223257-33bcc6a6-d681-4fc9-a137-c65889e58782.png)

![image](https://user-images.githubusercontent.com/5359825/130223321-5b068145-9d00-4c77-bdcc-53693d2fcda1.png)

The error messages would be more helpful if they had access to sourcemaps (browsers will pick them up automatically obviously), they'd be like `can't access property Symbol(), element is null` at line 15 (or something like that)

When I install vue-frag and go to node_modules/vue-frag, I see only the dist folder, package.json and README.md
Since the original unminified source is not shipped in the package, it's not possible to "sourcemap" to any file

To show that my webpack configuration is correct, see what vuex.esm.js looks like (frag.esm.js was already shown above):
![image](https://user-images.githubusercontent.com/5359825/130223145-d60ed8ac-9b97-4b74-99ff-4c9895ddf388.png)

**Comment by 3nuc** [comment]
I think changing main: in package.json to unminified sources should do the trick

same issue as https://github.com/IdentityModel/oidc-client-js/issues/753

**Comment by privatenumber** [comment]
Good call. I forgot about the source maps.

I will not publish `src` because it's allowed to assume specific bundler configuration (which will not be available in consuming builds), but I will add minified and non-minified versions.

**Comment by 3nuc** [comment]
![image](https://user-images.githubusercontent.com/5359825/130403329-5a45c365-6c3a-438a-b0fd-bd0325c5006a.png)
Error message is much more detailed now. Thanks!

**Comment by privatenumber** [comment]
If you're encountering a bug, feel free to open another issue 👍
