### ISSUE TITLE
adding "name" field to the fragment component

### ISSUE THREAD

**Issue by ReinisV** [privatenumber/vue-frag#59]
Could you add a "name" field to the fragment component? So that it doesnt show up as "Anonymous Component" in error msgs and in Vue Devtools?

**Comment by privatenumber** [comment]
Sure, feel free to PR it in!

**Comment by ReinisV** [comment]
https://github.com/privatenumber/vue-frag/pull/60

**Comment by privatenumber** [comment]
Released in 1.4.0. Thanks!
