### ISSUE TITLE
Not SSR compatible

### ISSUE THREAD

**Issue by mrleblanc101** [privatenumber/vue-frag#62]
Is there a way to make this work with Nuxt SSR ?
Maybe this is expected as this hack the v-dom, but currently I get :
> vue.runtime.esm.js?2b0e:619 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside `<p>`, or missing `<tbody>`. Bailing hydration and performing full client-side render.

**Comment by privatenumber** [comment]
Can you provide a link to a reproduction repository to demonstrate the problem?

**Comment by mrleblanc101** [comment]
Yeah, maybe tomorrow

**Comment by privatenumber** [comment]
Closing till reproduction is provided
