### ISSUE TITLE
你好，请问一下，递归组件情况下的问题

### ISSUE THREAD

**Issue by MaJiaXuan** [privatenumber/vue-frag#66]
我这边使用了vue-frag，进行递归组件操作。但是发现第一层生效，在动态加减数据的时候发现递归的里面都不生效。

![image](https://user-images.githubusercontent.com/24503453/190659940-4d0574f0-3494-43be-a987-71f43d25de21.png)
![image](https://user-images.githubusercontent.com/24503453/190660341-b1b75298-b65c-44eb-971a-4a967407ea25.png)

**Comment by MaJiaXuan** [comment]
使用版本是 1.4.1

**Comment by privatenumber** [comment]
Sorry, I tried using Google Translate but I don’t understand.

Can you provide a minimal reproduction of the problem you're experiencing and an English description of what you expect?

**Comment by MaJiaXuan** [comment]
hello I used 'Vue-frag' for recursive component encapsulation, but noticed that when I was dynamically adding or subtracting data, the view did not render the updated DOM, only the first rendering.

Refer to the two pictures posted above.

version: 1.4.1

**Comment by MaJiaXuan** [comment]
> 抱歉，我尝试使用谷歌翻译，但我不明白。
> 
> 您能否提供您遇到的问题的最小复制以及您期望的英文描述？

2

**Comment by MaJiaXuan** [comment]
help.In a hurry, I tried to replace 'Vue-frag' with a 'div' tag and it worked, but I didn't want to have an extra tag at each level of recursion.

**Comment by privatenumber** [comment]
Please provide a link to a minimal reproduction repository.

**Comment by privatenumber** [comment]
Will re-open once reproduction is provided
