### ISSUE TITLE
firstChild working error

### ISSUE THREAD

**Issue by dsssc** [privatenumber/vue-frag#71]
### Problem

while i use createDocumentFragment with appendChild, it break infinite loop
`
const el = document.createDocumentFragment()

const p = value
 while (p.firstChild) {
      el.appendChild(p.firstChild)
 }
`

### Expected behavior

`
const el = document.createDocumentFragment()

const p = value
 while (p.firstChild) {
      el.appendChild(p.firstChild)
 }
`

### Minimal reproduction URL

*

### Version

1.4.3

### Node.js version

v20.16.0

### Package manager

pnpm

### Operating system

Windows

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Sorry, I don't understand what you're reporting.

Please elaborate and if possible, provide a reproduction, and we can re-open this.
