### ISSUE TITLE
v if on v-frag not working

### ISSUE THREAD

**Issue by im-gasay** [privatenumber/vue-frag#8]
When i set showAuthModal on true, he showing AuthModalComponent, but when i set showAuthModal on false,  AuthModalComponent not hidden. show|hide wokring by v-if

Component by i call v-if
![image](https://user-images.githubusercontent.com/26240575/94011973-f6daa700-fdc9-11ea-8058-e52cb3c45125.png)

Called component - AuthModalComponent
![image](https://user-images.githubusercontent.com/26240575/94012036-0d80fe00-fdca-11ea-88b1-7ab4402d6a9e.png)

Console error in Chrome devtool 
![image](https://user-images.githubusercontent.com/26240575/94012222-4f11a900-fdca-11ea-87eb-7523d5b1fef0.png)

Sorry for my english. I from Russia

**Comment by privatenumber** [comment]
Thanks for the issue @im-gasay !

I think I was able to reproduce this [here](https://jsfiddle.net/hirokiosame/05uvwfc7/).

Will look into it over the weekend.

**Comment by privatenumber** [comment]
@im-gasay 

Should be fixed in version 1.1.2: [Demo](https://jsfiddle.net/hirokiosame/sna5b4yf/)

Let me know if the issue still exists
